// File generated by FlutterFire CLI.
// To use with only Android, you can ignore other platform values.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zcHiddNA1fS70chCstiFCNinXAZePbo',
    authDomain: 'medinfo-86a58.firebaseapp.com',
    projectId: 'medinfo-86a58',
    storageBucket: 'medinfo-86a58.firebasestorage.app',
    messagingSenderId: '563072773656',
    appId: '1:563072773656:web:REPLACE_WITH_WEB_APP_ID',
    measurementId: 'G-REPLACE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8zcHiddNA1fS70chCstiFCNinXAZePbo',
    appId: '1:563072773656:android:558ed7d10bf1a223a75d6d',
    messagingSenderId: '563072773656',
    projectId: 'medinfo-86a58',
    storageBucket: 'medinfo-86a58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8zcHiddNA1fS70chCstiFCNinXAZePbo',
    appId: '1:563072773656:ios:REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '563072773656',
    projectId: 'medinfo-86a58',
    storageBucket: 'medinfo-86a58.firebasestorage.app',
    iosClientId: '563072773656-REPLACE.apps.googleusercontent.com',
    iosBundleId: 'REPLACE_WITH_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8zcHiddNA1fS70chCstiFCNinXAZePbo',
    appId: '1:563072773656:macos:REPLACE_WITH_MACOS_APP_ID',
    messagingSenderId: '563072773656',
    projectId: 'medinfo-86a58',
    storageBucket: 'medinfo-86a58.firebasestorage.app',
    iosClientId: '563072773656-REPLACE.apps.googleusercontent.com',
    iosBundleId: 'REPLACE_WITH_IOS_BUNDLE_ID',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8zcHiddNA1fS70chCstiFCNinXAZePbo',
    appId: '1:563072773656:windows:REPLACE_WITH_WINDOWS_APP_ID',
    messagingSenderId: '563072773656',
    projectId: 'medinfo-86a58',
    storageBucket: 'medinfo-86a58.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA8zcHiddNA1fS70chCstiFCNinXAZePbo',
    appId: '1:563072773656:linux:REPLACE_WITH_LINUX_APP_ID',
    messagingSenderId: '563072773656',
    projectId: 'medinfo-86a58',
    storageBucket: 'medinfo-86a58.firebasestorage.app',
  );
}
